# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            TechInShanghai
tagline:          Podcast by host John Vallis
description:      "PODCAST INTERVIEWS WITH THE PEOPLE BEHIND IT ALL"
url:
baseurl:         ""

author:
  name:           'John Vallis'
  url:            https://twitter.com/karloespiritu

# Custom vars
version:          1.0.0

github:
  repo:
